language: java

services:
  - docker

jdk:
  - openjdk8

jobs:
  include:
    - stage: deploy
      name: "build docker image"
      if: branch = feature/docker
      script:
        - docker build -t wangyuheng/pharos .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag wangyuheng/pharos:1.0.0 wangyuheng/pharos:latest
        - docker push wangyuheng/pharos
notifications:
  email:
    - wangyuheng@outlook.com