language: java

services:
  - docker

jdk:
  - openjdk8

jobs:
  include:
    - stage: test
      name: "Run test cases"
      if: tag IS blank
      script: mvn test
    - stage: deploy
      name: "Build & Push docker image with tag"
      if: tag IS present
      script:
        - mvn clean package -Ddocker.repository=wangyuheng -Ddocker.tag=$TRAVIS_TAG
        - docker tag wangyuheng/pharos:$TRAVIS_TAG wangyuheng/pharos:latest
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push wangyuheng/pharos

notifications:
  email:
    - wangyuheng@outlook.com