language: java

services:
  - docker

jdk:
  - openjdk8

jobs:
  include:
    - stage: docker
      name: "Build & Push docker image"
      if: branch = master
      script:
        - docker build -t wangyuheng/pharos .
        - docker tag wangyuheng/pharos wangyuheng/pharos:1.0.0
        - docker tag wangyuheng/pharos wangyuheng/pharos:latest
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push wangyuheng/pharos

notifications:
  email:
    - wangyuheng@outlook.com